<?php
$this->headScript()->appendScript('$(function(){$("ul li.admin-area").addClass("active");})');

$headTitle = 'Edit category';
$this->headTitle($headTitle);

$form = $this->form;
$form->setAttributes([
    'action' => $this->url('admin/categories', ['page' => (int)$this->pageNumber, 'action' => 'edit', 'id' => (int)$this->id])
]);
$form->prepare();

$parentId = $form->get('parentId');
$parentId->setLabel($parentId->getLabel() . ' *');
$parentIdLabel = str_replace('*', '<strong class="label-star">*</strong>', $this->formLabel($parentId));

$name = $form->get('name');
$name->setLabel($name->getLabel() . ' *');
$nameLabel = str_replace('*', '<strong class="label-star">*</strong>', $this->formLabel($name));
?>
<div class="row well register-form-box">
    <div class="col-sm-10">
        <?php
        echo $this->form()->openTag($form);
        echo '<fieldset><legend>Form for editing category</legend><br>';
        echo $this->formHidden($form->get('csrf'));
        echo $this->formElementErrors($form->get('csrf'));
        ?>
        <div class="form-group">
            <?= $parentIdLabel ?>
            <div class="col-sm-9">
                <?= $this->formSelect($parentId) ?>
            </div>
        </div>
        <div class="form-group">
            <?= $nameLabel ?>
            <div class="col-sm-9">
                <?= $this->formText($name) ?>
                <?= $this->formElementErrors($name) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 col-sm-offset-3">
                <?= $this->formSubmit($form->get('submit')) ?>
            </div>
        </div>
        <?php
        echo '</fieldset>';
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
